# Generated by Django 2.0.2 on 2018-03-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calen', '0002_auto_20180305_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoon',
            name='poster',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
