# Generated by Django 2.0.2 on 2018-03-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calen', '0003_cartoon_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music',
            name='poster',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
