# Generated by Django 2.0.2 on 2018-03-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calen', '0004_auto_20180307_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoon',
            name='download',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
