# Generated by Django 2.0.2 on 2018-03-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calen', '0005_cartoon_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='download',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music',
            name='download',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
